<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="ResourceMessagesException.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ResourceMessagesException.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="ResourceMessagesException.pt-PT.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ResourceMessagesException.pt-PT.Designer.cs</LastGenOutput>
      <CustomToolNamespace>MyRecipeBook.Exceptions</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="ResourceMessagesException.pt-BR.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ResourceMessagesException.pt-BR.Designer.cs</LastGenOutput>
      <CustomToolNamespace>MyRecipeBook.Exceptions</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="ResourceMessagesException.fr.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ResourceMessagesException.fr.Designer.cs</LastGenOutput>
      <CustomToolNamespace>MyRecipeBook.Exceptions</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="ResourceMessagesException.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ResourceMessagesException.Designer.cs</LastGenOutput>
      <CustomToolNamespace>MyRecipeBook.Exceptions</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>

</Project>
